name: Test

on: [ 'push' ]

jobs:
  psalm:
    name: php unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 8.1
          - 8.2
        composer:
          - ""
          - "--prefer-lowest"
          - "--prefer-stable"
          - "--prefer-higher"
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install
      - name: Run tests
        run: composer test